#!/usr/bin/env python3
"""Gera componente de legendas word-by-word para Remotion a partir de transcricao."""

import argparse
import json
import os
import sys
from pathlib import Path


SUBTITLE_COMP_TEMPLATE = """// Auto-generated by content-remotion generate_subtitle_comp.py
// Estilo: {style} | Video: {video_name}

import React from "react";
import {{ useCurrentFrame, interpolate }} from "remotion";

interface Word {{
  text: string;
  startFrame: number;
  endFrame: number;
}}

const words: Word[] = {json_words};

const STYLES = {{
  hormozi: {{
    activeColor: "#FFD700",
    inactiveColor: "#FFFFFF",
    bgOpacity: 0.85,
    fontSize: 40,
    fontWeight: 800,
    bgPadding: "6px 4px",
    bgRadius: 6,
  }},
  clean: {{
    activeColor: "#FFFFFF",
    inactiveColor: "#AAAAAA",
    bgOpacity: 0.6,
    fontSize: 36,
    fontWeight: 600,
    bgPadding: "4px 2px",
    bgRadius: 4,
  }},
  bold: {{
    activeColor: "#00FF88",
    inactiveColor: "#FFFFFF",
    bgOpacity: 0.9,
    fontSize: 48,
    fontWeight: 900,
    bgPadding: "8px 6px",
    bgRadius: 8,
  }},
  neon: {{
    activeColor: "#FF00FF",
    inactiveColor: "#CCCCCC",
    bgOpacity: 0.7,
    fontSize: 38,
    fontWeight: 700,
    bgPadding: "6px 4px",
    bgRadius: 6,
  }},
}};

export const DynamicSubtitles: React.FC = () => {{
  const frame = useCurrentFrame();
  const s = STYLES.{style};

  const activeWordIndex = words.findIndex(
    (w) => frame >= w.startFrame && frame <= w.endFrame
  );
  if (activeWordIndex === -1) return null;

  const visibleWords = words.filter((w) => w.endFrame <= words[activeWordIndex].endFrame);
  const lines: Word[][] = [];
  const maxPerLine = {max_per_line};
  for (let i = 0; i < visibleWords.length; i += maxPerLine) {{
    lines.push(visibleWords.slice(i, i + maxPerLine));
  }}

  const topOffset = "{position}" === "center" ? "45%" : undefined;
  const bottomOffset = "{position}" === "bottom" ? 200 : undefined;

  return (
    <div
      style={{{{{
        position: "absolute",
        left: "5%",
        right: "5%",
        top: topOffset,
        bottom: bottomOffset,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 8,
      }}}}
    >
      {{lines.map((line, lineIdx) => (
        <div key={{lineIdx}} style={{{{{
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "center",
          gap: 3,
        }}}}>
          {{line.map((word, wordIdx) => {{
            const isActive = frame >= word.startFrame && frame <= word.endFrame;
            const wordPop = isActive
              ? interpolate(frame, [word.startFrame, word.startFrame + 4], [1, 1.12], {{
                  extrapolateLeft: "clamp",
                  extrapolateRight: "clamp",
                }})
              : 1;
            return (
              <span
                key={{wordIdx}}
                style={{{{{
                  fontSize: s.fontSize,
                  fontWeight: s.fontWeight,
                  color: isActive ? s.activeColor : s.inactiveColor,
                  backgroundColor: `rgba(0,0,0,${{s.bgOpacity}})`,
                  padding: s.bgPadding,
                  borderRadius: s.bgRadius,
                  transform: `scale(${{wordPop}})`,
                  display: "inline-block",
                  textShadow: "0 2px 4px rgba(0,0,0,0.5)",
                }}}}
              >
                {{word.text}}
              </span>
            );
          }})}}
        </div>
      ))}}
    </div>
  );
}};
"""


def load_transcription(video_path: str) -> list:
    base = os.path.splitext(video_path)[0]
    candidates = [
        f"{base}_legendas.json",
        f"{base}_remotion_subtitles.json",
        f"{base}.json",
    ]
    for path in candidates:
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            if "words" in data:
                return data["words"]
            if isinstance(data, list):
                return data
    return []


def main():
    parser = argparse.ArgumentParser(
        description="Gera componente de legendas word-by-word"
    )
    parser.add_argument("--video", required=True, help="Video de entrada")
    parser.add_argument("--saida", default=None, help="Diretorio de saida")
    parser.add_argument(
        "--estilo", default="hormozi", choices=["hormozi", "clean", "bold", "neon"]
    )
    parser.add_argument("--posicao", default="bottom", choices=["bottom", "center"])
    parser.add_argument(
        "--palavras-por-linha",
        type=int,
        default=6,
        help="Max palavras por linha (default: 6)",
    )
    parser.add_argument("--fps", type=int, default=30)
    args = parser.parse_args()

    words = load_transcription(args.video)
    if not words:
        print("ERRO: Nenhuma transcricao encontrada.")
        print(f"  Gere legendas primeiro com content-editing: /legendas {args.video}")
        sys.exit(1)

    remotion_words = []
    for w in words:
        start = w.get("start", 0)
        end = w.get("end", start + 0.5)
        text = w.get("word", "").strip()
        if text:
            remotion_words.append(
                {
                    "text": text,
                    "startFrame": int(start * args.fps),
                    "endFrame": int(end * args.fps),
                }
            )

    comp = SUBTITLE_COMP_TEMPLATE.format(
        style=args.estilo,
        video_name=os.path.basename(args.video),
        json_words=json.dumps(remotion_words, ensure_ascii=False, indent=2),
        max_per_line=args.palavras_por_linha,
        position=args.posicao,
    )

    if args.saida:
        out_dir = Path(args.saida)
        out_dir.mkdir(parents=True, exist_ok=True)
        comp_path = out_dir / f"Subtitles_{args.estilo}.tsx"
    else:
        comp_path = Path(f"Subtitles_{args.estilo}.tsx")

    with open(comp_path, "w", encoding="utf-8") as f:
        f.write(comp)

    print(f"Componente gerado: {comp_path}")
    print(f"  Palavras: {len(remotion_words)}")
    print(f"  Estilo: {args.estilo}")
    print(f"  Duracao: {int(max(w['endFrame'] for w in remotion_words) / args.fps)}s")


if __name__ == "__main__":
    main()
