#!/usr/bin/env python3
"""Gera composicao Remotion dopaminergica a partir de video e transcricao."""

import argparse
import json
import os
import sys
from pathlib import Path

try:
    import requests
except ImportError:
    print("Instale requests: pip3 install requests")
    sys.exit(1)


REMOTION_COMP_TEMPLATE = """// Auto-generated by content-remotion generate_dopamine_comp.py
// Composicao dopaminergica para: {video_name}
// Estilo: {style} | Plataforma: {plataforma}

import React from "react";
import {{
  Composition,
  AbsoluteFill,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  spring,
  Easing,
  Sequence,
}} from "remotion";

interface SubtitleWord {{
  text: string;
  startFrame: number;
  endFrame: number;
}}

interface ZoomPoint {{
  frame: number;
  scale: number;
  duration: number;
}}

export const DopamineVideo: React.FC = () => {{
  const frame = useCurrentFrame();
  const {{ fps, durationInFrames }} = useVideoConfig();

  const subtitles: SubtitleWord[] = {json_subtitles};
  const zoomPoints: ZoomPoint[] = {json_zoom_points};

  const zoomScale = getZoomScale(frame, zoomPoints);
  const isHookPhase = frame < fps * 3;
  const isCTAPhase = frame > durationInFrames - fps * 5;

  const hookOpacity = isHookPhase
    ? interpolate(frame, [0, 15], [0, 1], {{ extrapolateLeft: "clamp", extrapolateRight: "clamp" }})
    : interpolate(frame, [fps * 3, fps * 3.5], [1, 0], {{ extrapolateLeft: "clamp", extrapolateRight: "clamp" }});

  const hookScale = spring({{ frame, fps, config: {{ damping: 12, stiffness: 200 }} }});
  const ctaOpacity = isCTAPhase
    ? interpolate(frame, [durationInFrames - fps * 3, durationInFrames - fps * 2.5], [0, 1], {{ extrapolateLeft: "clamp", extrapolateRight: "clamp" }})
    : 0;

  const currentWords = subtitles.filter(
    (w) => frame >= w.startFrame && frame <= w.endFrame
  );

  return (
    <AbsoluteFill style={{{{ backgroundColor: "#000" }}}}>
      <AbsoluteFill
        style={{{ transform: `scale(${{zoomScale}})` }}}}
      >
        <video
          src="{video_src}"
          style={{{{ width: "100%", height: "100%", objectFit: "cover" }}}}
          muted
        />
      </AbsoluteFill>

      <div style={{{{ position: "absolute", top: 0, left: 0, width: "100%", height: 80, backgroundColor: "rgba(0,0,0,0.3)" }}}} />
      <div style={{{{ position: "absolute", bottom: 0, left: 0, width: "100%", height: 200, background: "linear-gradient(transparent, rgba(0,0,0,0.8))" }}}} />

      {hookText && (
        <div style={{{ position: "absolute", top: 100, left: "50%", transform: `translateX(-50%) scale(${{hookScale}})`, opacity: hookOpacity, textAlign: "center", width: "90%" }}}>
          <div style={{{{ fontSize: 52, fontWeight: 900, color: "#fff", textShadow: "0 4px 20px rgba(0,0,0,0.8)", lineHeight: 1.2 }}}}>
            {hook_text}
          </div>
        </div>
      )}

      {currentWords.length > 0 && (
        <div style={{{{ position: "absolute", bottom: 220, left: "50%", transform: "translateX(-50%)", width: "90%", display: "flex", flexWrap: "wrap", justifyContent: "center", gap: 4 }}}}>
          {{subtitles
            .filter((w) => w.endFrame <= currentWords[0].endFrame)
            .map((word, i) => {{
              const isActive = frame >= word.startFrame && frame <= word.endFrame;
              const wordScale = isActive
                ? interpolate(frame, [word.startFrame, word.startFrame + 5], [1, 1.15], {{ extrapolateLeft: "clamp", extrapolateRight: "clamp" }})
                : 1;
              return (
                <span
                  key={{i}}
                  style={{{{ fontSize: 42, fontWeight: 700, color: isActive ? "{brand_color}" : "#ffffff", transform: `scale(${{wordScale}})`, textShadow: "0 2px 8px rgba(0,0,0,0.9)", display: "inline-block" }}}}
                >
                  {{word.text}}
                </span>
              );
            }})}}
        </div>
      )}

      {ctaText && ctaOpacity > 0 && (
        <div style={{{{ position: "absolute", bottom: 120, left: "50%", transform: "translateX(-50%)", opacity: ctaOpacity, backgroundColor: "{brand_color}", borderRadius: 16, padding: "16px 32px", textAlign: "center" }}}}>
          <div style={{{{ fontSize: 36, fontWeight: 800, color: "#000" }}}}>
            {cta_text}
          </div>
          <div style={{{{ fontSize: 20, color: "#333", marginTop: 4 }}}}>
            👆 Comente sua resposta
          </div>
        </div>
      )}
    </AbsoluteFill>
  );
}};

function getZoomScale(frame: number, zoomPoints: ZoomPoint[]): number {{
  if (zoomPoints.length === 0) return 1;
  for (const point of zoomPoints) {{
    if (frame >= point.frame && frame < point.frame + point.duration) {{
      const progress = (frame - point.frame) / point.duration;
      const eased = Easing.out(Easing.cubic(progress));
      return interpolate(eased, [0, 1], [1, point.scale]);
    }}
  }}
  return 1;
}}
"""


def load_subtitles(video_path: str) -> list:
    base = os.path.splitext(video_path)[0]
    for ext in ["_legendas.json", "_remotion_subtitles.json", "_analise.json"]:
        path = f"{base}{ext}"
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            if "words" in data:
                return data["words"]
            if "subtitle_data" in data:
                return data["subtitle_data"].get("words", [])
    return []


def words_to_remotion(words: list, fps: int = 30) -> list:
    result = []
    for w in words:
        start = w.get("start", 0)
        end = w.get("end", start + 0.5)
        text = w.get("word", "").strip()
        if text:
            result.append(
                {
                    "text": text,
                    "startFrame": int(start * fps),
                    "endFrame": int(end * fps),
                }
            )
    return result


def generate_zoom_points(words: list, style: str = "rapido", fps: int = 30) -> list:
    zoom_points = []
    interval = 3 if style == "rapido" else 5 if style == "medio" else 8

    if not words:
        return zoom_points

    max_frame = max(w.get("endFrame", 0) for w in words) if words else 0

    frame = fps * 3
    while frame < max_frame - fps * 5:
        current_words = [w for w in words if w["startFrame"] <= frame <= w["endFrame"]]
        scale = 1.25 if style == "rapido" else 1.15 if style == "medio" else 1.1
        duration = int(fps * 0.5) if style == "rapido" else int(fps * 0.8)

        if current_words:
            zoom_points.append(
                {
                    "frame": frame,
                    "scale": scale,
                    "duration": duration,
                }
            )

        frame += int(fps * interval)

    return zoom_points[:30]


def generate_comp(args):
    words = load_subtitles(args.video)
    remotion_words = words_to_remotion(words, args.fps)

    zoom_points = generate_zoom_points(remotion_words, args.estilo, args.fps)

    video_name = os.path.basename(args.video)
    video_src = video_name

    hook_text = args.hook or ""
    cta_text = args.cta or ""
    brand_color = args.cor or "#FFD700"

    comp = REMOTION_COMP_TEMPLATE.format(
        video_name=video_name,
        style=args.estilo,
        plataforma=args.plataforma,
        json_subtitles=json.dumps(remotion_words, ensure_ascii=False, indent=6),
        json_zoom_points=json.dumps(zoom_points, indent=6),
        video_src=video_src,
        hook_text=hook_text,
        cta_text=cta_text,
        brand_color=brand_color,
    )

    if args.saida:
        out_dir = Path(args.saida)
        out_dir.mkdir(parents=True, exist_ok=True)
        comp_path = (
            out_dir / f"Dopamine{video_name.replace('.mp4', '').replace('.', '_')}.tsx"
        )
    else:
        comp_path = Path(
            f"Dopamine{video_name.replace('.mp4', '').replace('.', '_')}.tsx"
        )

    with open(comp_path, "w", encoding="utf-8") as f:
        f.write(comp)

    print(f"Composicao gerada: {comp_path}")
    print(f"  Palavras: {len(remotion_words)}")
    print(f"  Zoom points: {len(zoom_points)}")
    print(f"  Estilo: {args.estilo}")
    print(
        f"  Duracao estimada: {int(max(w['endFrame'] for w in remotion_words) / args.fps) if remotion_words else 0}s"
    )

    return str(comp_path)


def main():
    parser = argparse.ArgumentParser(
        description="Gera composicao Remotion dopaminergica"
    )
    parser.add_argument("--video", required=True, help="Video de entrada")
    parser.add_argument("--cliente", default=None, help="Nome do cliente")
    parser.add_argument("--saida", default=None, help="Diretorio de saida")
    parser.add_argument(
        "--estilo", default="rapido", choices=["rapido", "medio", "cinematico"]
    )
    parser.add_argument(
        "--plataforma", default="reels", choices=["reels", "shorts", "tiktok", "feed"]
    )
    parser.add_argument(
        "--fps", type=int, default=30, help="Frames por segundo (default: 30)"
    )
    parser.add_argument("--hook", default=None, help="Texto do hook")
    parser.add_argument("--cta", default=None, help="Texto do CTA")
    parser.add_argument("--cor", default="#FFD700", help="Cor de destaque (hex)")
    args = parser.parse_args()

    generate_comp(args)


if __name__ == "__main__":
    main()
